version: '3'

services:
  producer:
    image: perftest-producer
    build: 
      context: ./sources/perftest
      dockerfile: src/PerfTest.Producer/Dockerfile      
    deploy:
      replicas: 2
    depends_on:
      rabbit:
        condition: service_healthy
    environment:       
      - 'ConnectionStrings__Rabbit=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbit/'
      - 'Producer__MaxSendConcurrency=25'
      - 'Producer__MaxSendCount=100000'

  consumer:    
    image: perftest-consumer    
    build: 
      context: ./sources/perftest
      dockerfile: src/PerfTest.Consumer/Dockerfile  
    depends_on:
      rabbit:
        condition: service_healthy
    volumes:
      - ./reports:/app/reports    
    environment:       
      - 'ConnectionStrings__Rabbit=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbit/'     
      - 'Consumer__ReportPath=/app/reports'

  rabbit:
    build: ./services/rabbitmq/
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_MGMT_PORT}:15672"
    volumes:
      - './data/rabbitmq/:/var/lib/rabbitmq/mnesia/:cached'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBIT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}'